version: '3.7'

services:
  uzr:
    build:
      context: .
      args:
        UZR_ADMIN_USER: $UZR_ADMIN_USER
        UZR_ADMIN_PW: $UZR_ADMIN_PW
    volumes:
      - uzrdb:/etc

    ports:
      - 8080:8080

volumes:
  uzrdb:
