name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    strategy:
      matrix:
        include:
        - CC: gcc
          CXX: g++

        - CC: clang
          CXX: clang++

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -DCMAKE_C_COMPILER=${{ matrix.CC }} ..
        cmake --build .

    - name: Run unit tests
      run: ./build/test_uzr

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run e2e tests
      run: ./test.sh
